"""CORRECT self-collision blacklist for OpenArm.

Generated by gen_blacklist_openarm.py.
Blacklist = ONLY pairs that carry no collision signal:
  permanent-overlap (max signed dist < 0), rigidly-fixed
  (constant distance), or parent-child (URDF).
Pairs that can separate AND collide are KEPT (model must
learn them).  Inter-arm pairs are never blacklisted.
Samples: 199990.
"""

BLACKLIST_NAME_PAIRS = [
    ("openarm_body_link0", "openarm_left_link0"),  # parent-child
    ("openarm_body_link0", "openarm_left_link1"),  # rigid-fixed(d=18mm)
    ("openarm_body_link0", "openarm_right_link0"),  # parent-child
    ("openarm_body_link0", "openarm_right_link1"),  # rigid-fixed(d=18mm)
    ("openarm_left_hand", "openarm_left_hand_tcp"),  # parent-child(unseen)
    ("openarm_left_hand", "openarm_left_left_finger"),  # parent-child
    ("openarm_left_link0", "openarm_left_link1"),  # parent-child
    ("openarm_left_link0", "openarm_left_link2"),  # rigid-fixed(d=9mm)
    ("openarm_left_link1", "openarm_left_link2"),  # parent-child
    ("openarm_left_link2", "openarm_left_link3"),  # parent-child
    ("openarm_left_link3", "openarm_left_link4"),  # parent-child
    ("openarm_left_link4", "openarm_left_link5"),  # parent-child
    ("openarm_left_link5", "openarm_left_link6"),  # parent-child
    ("openarm_left_link6", "openarm_left_link7"),  # parent-child
    ("openarm_left_link7", "openarm_left_hand"),  # parent-child
    ("openarm_left_link7", "openarm_left_left_finger"),  # rigid-fixed(d=4mm)
    ("openarm_right_hand", "openarm_right_hand_tcp"),  # parent-child(unseen)
    ("openarm_right_hand", "openarm_right_right_finger"),  # parent-child
    ("openarm_right_link0", "openarm_right_link1"),  # parent-child
    ("openarm_right_link0", "openarm_right_link2"),  # rigid-fixed(d=9mm)
    ("openarm_right_link1", "openarm_right_link2"),  # parent-child
    ("openarm_right_link2", "openarm_right_link3"),  # parent-child
    ("openarm_right_link3", "openarm_right_link4"),  # parent-child
    ("openarm_right_link4", "openarm_right_link5"),  # parent-child
    ("openarm_right_link5", "openarm_right_link6"),  # parent-child
    ("openarm_right_link6", "openarm_right_link7"),  # parent-child
    ("openarm_right_link7", "openarm_right_hand"),  # parent-child
    ("openarm_right_link7", "openarm_right_right_finger"),  # rigid-fixed(d=4mm)
    ("openarm_left_hand", "openarm_left_right_finger"),  # permanent-overlap(-8mm); gen missed, caught by 500k verify
    ("openarm_right_hand", "openarm_right_left_finger"),  # permanent-overlap(-8mm); gen missed, caught by 500k verify
    ("openarm_left_link7", "openarm_left_right_finger"),  # rigid-fixed(+4mm); end-effector cluster
    ("openarm_right_link7", "openarm_right_left_finger"),  # rigid-fixed(+4mm); end-effector cluster
    # CRITICAL: the two jaws of EACH gripper are fixed (fingers held at 0.01), so
    # their gap is CONSTANT 14.5mm -- zero collision signal, zero gradient.  Left
    # unblacklisted it dominated the min-distance label on 66% of configs, pinning
    # gamma~14.5mm with ~0 gradient and capping grad_cos at ~0.45.  (diag 2026-06)
    ("openarm_left_left_finger", "openarm_left_right_finger"),   # intra-gripper, fixed 14.5mm
    ("openarm_right_left_finger", "openarm_right_right_finger"),  # intra-gripper, fixed 14.5mm
    # link5<->link7: same-arm adjacent structural pair (via link6); true collisions only 0.04%, but coarse-decomp residual over-detection ~0.6%,
    # and barrier control of the end-effector evasion cannot reach intra-arm structural pairs -> re-blacklisted (found in 2026-06-27 eval)
    ("openarm_left_link5", "openarm_left_link7"),
    ("openarm_right_link5", "openarm_right_link7"),
]
